### ISSUE TITLE
Diff bug

### ISSUE THREAD

**Issue by bstst** [praneshr/react-diff-viewer#32]
Diffing seems to break when new content has no repeated content compared with the old one, reproduced here https://stackblitz.com/edit/react-skqpxu

**Comment by praneshr** [comment]
This is a good catch. I'll look into it shortly.

**Comment by jrsquared** [comment]
Ran into this too

**Comment by cczz598** [comment]
I just wanna know, when will fix this problem？🥺

**Comment by praneshr** [comment]
Hey guys, there’s a PR pending. I’ll merge the change next week. Sorry for the delay.

**Comment by dlsgusrn7577** [comment]
Dear praneshr,

Is there any update on this bug?
Thanks.

**Comment by praneshr** [comment]
I'll release a patch by this weekend. I'm really sorry for this delay.

**Comment by dlsgusrn7577** [comment]
Sounds good :) Thanks!

**Comment by praneshr** [comment]
Released a patch to address this issue. You can try it by installing the beta version.

```
yarn add react-diff-viewer@beta
```

I'll wait for a few more days before pushing it to production. Sorry for the long delay.

**Comment by willhighland** [comment]
Just wanted to let you know that the `@beta` patch fixed this issue for me, thank you!

**Comment by praneshr** [comment]
Fixed in [v2.0.3](https://github.com/praneshr/react-diff-viewer/releases/tag/v2.0.3)

**Comment by Ionut-Milas** [comment]
@praneshr this is still not fixed.
Have a look here please:
https://stackblitz.com/edit/react-riskub

I added the v 2.0.3 but no luck
